### ISSUE TITLE
Front End User - Create a connection page

### ISSUE THREAD

**Issue by seobrand** [egortimofeev/genius#24]
I am not sure if I've seen the design for this page yet.  I am putting this in milestone 5, but depending upon the design status this may get moved into next week.

**Comment by Jenelle-SEO** [comment]
Make a Connection Page
https://notableapp.com/posts/de900f8b2d13fde87a4123028fd61549ce173d17

**Comment by Jenelle-SEO** [comment]
Complete approved by Jeff
