### ISSUE TITLE
Send Registration Email to User

### ISSUE THREAD

**Issue by seobrand** [egortimofeev/genius#7]
Email to contain credentials and email verification link

**Comment by egortimofeev** [comment]
done. as soon as we supplied SMTP credentials emails will be delivered

**Comment by Jenelle-SEO** [comment]
Hi Egor,

Can I get the URL for the following so I can plug them into the clickfunnel
system?

End User path (the URL to trigger the password email call)

Developer Path (the URL to trigger the password for the Developer).

Thanks - Jenelle

On Thu, Mar 19, 2015 at 8:16 AM, Egor Timofeev <notifications@github.com>
wrote:

> Closed #7 <https://github.com/egortimofeev/genius/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egortimofeev/genius/issues/7#event-259304195>.
>



-- 
Jenelle Ford
Skype: Jenelle_SEO

**Comment by egortimofeev** [comment]
Hi Jenelle,

For developer please use http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com
For end user we do not have it yet as we never discussed it. We can implement it today. It will be geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com. And we do not have page for registering regular user. We can use template of developer registration page. Please confirm if we need o implement it.

**Comment by Jenelle-SEO** [comment]
Thank you Egor.  Yes please use the same template.

Thanks - Jenelle

On Thu, Mar 19, 2015 at 11:13 AM, Egor Timofeev <notifications@github.com>
wrote:

> Hi Jenelle,
>
> For developer please use
> http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com
> For end user we do not have it yet as we never discussed it. We can
> implement it today. It will be
> geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com. And we do
> not have page for registering regular user. We can use template of
> developer registration page. Please confirm if we need o implement it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/egortimofeev/genius/issues/7#issuecomment-83619156>.
>



-- 
Jenelle Ford
Skype: Jenelle_SEO

**Comment by Jenelle-SEO** [comment]
Please verify emails


On Thu, Mar 19, 2015 at 11:21 AM, Jenelle Ford <jenelle@seobrand.net> wrote:

> Thank you Egor.  Yes please use the same template.
>
> Thanks - Jenelle
>
> On Thu, Mar 19, 2015 at 11:13 AM, Egor Timofeev <notifications@github.com>
> wrote:
>
>> Hi Jenelle,
>>
>> For developer please use
>> http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com
>> For end user we do not have it yet as we never discussed it. We can
>> implement it today. It will be
>> geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com. And we
>> do not have page for registering regular user. We can use template of
>> developer registration page. Please confirm if we need o implement it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/egortimofeev/genius/issues/7#issuecomment-83619156>.
>>
>
>
>
> --
> Jenelle Ford
> Skype: Jenelle_SEO
>



-- 
Jenelle Ford
Skype: Jenelle_SEO

**Comment by Jenelle-SEO** [comment]
Please verify emails

For developer please use
http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com

should be http://geniusbutter.com/auth/registerFull?email
<http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com>  ??

For end user geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com

should be geniusbutter.com/auth/registerSimple?email
<http://geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com>  ??

Thanks!

On Thu, Mar 19, 2015 at 11:41 AM, Jenelle Ford <jenelle@seobrand.net> wrote:

> Please verify emails
>
>
> On Thu, Mar 19, 2015 at 11:21 AM, Jenelle Ford <jenelle@seobrand.net>
> wrote:
>
>> Thank you Egor.  Yes please use the same template.
>>
>> Thanks - Jenelle
>>
>> On Thu, Mar 19, 2015 at 11:13 AM, Egor Timofeev <notifications@github.com
>> > wrote:
>>
>>> Hi Jenelle,
>>>
>>> For developer please use
>>> http://geniusbutter.com/auth/registerFull?email=egor%40seobrand.com
>>> For end user we do not have it yet as we never discussed it. We can
>>> implement it today. It will be
>>> geniusbutter.com/auth/registerSimple?email=egor%40seobrand.com. And we
>>> do not have page for registering regular user. We can use template of
>>> developer registration page. Please confirm if we need o implement it.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/egortimofeev/genius/issues/7#issuecomment-83619156>.
>>>
>>
>>
>>
>> --
>> Jenelle Ford
>> Skype: Jenelle_SEO
>>
>
>
>
> --
> Jenelle Ford
> Skype: Jenelle_SEO
>



-- 
Jenelle Ford
Skype: Jenelle_SEO

**Comment by Jenelle-SEO** [comment]
SMTP

please try
 general@geniusbutter.com
jen6565connect

**Comment by Jenelle-SEO** [comment]
Please let me know when you've had the chance to test the SMTP info

**Comment by egortimofeev** [comment]
Jenelle,

Can you please let me know SMTP server details? So I need: server address, port.
As soon as I get it I will be able to test.

Thank you
Egor

**Comment by egortimofeev** [comment]
URL to use for developer: 
http://geniusbutter.com/auth/registerFull?email=[PUT YOUR EMAIL HERE]

URL to use for regular user: 
http://geniusbutter.com/auth/registerSimple?email=[PUT YOUR EMAIL HERE]

**Comment by Jenelle-SEO** [comment]
Hey Egor,

Here they are:

Gmail SMTP server address: smtp.gmail.com
Gmail SMTP user name: Your full Gmail address (e.g. example@gmail.com)
Gmail SMTP password: Your Gmail password
With Gmail 2-step authentication enabled, use an application-specific Gmail password.
Gmail SMTP port (TLS): 587
Gmail SMTP port (SSL): 465
Gmail SMTP TLS/SSL required: yes

**Comment by Jenelle-SEO** [comment]
Egor - please see SMTP details sent on Monday.

**Comment by Jenelle-SEO** [comment]
Chris & Jeff

The login for the gmail account doesn't work

general@geniusbutter.com
jen6565connect

Can you please check the account and see if you're able to login?

I can't and email bounces went sent.

Thanks!

**Comment by rugly** [comment]
The email address is actually "General Genius" <connect@geniusbutter.com>, and I just tested those credentials successfully.   Going forward I'd like us to keep all credentials (user name/password) out of the source code and project assets (wiki, docs, etc)  - we should be creating new passwords with Dashlane and sharing them there, and should set up Chef or similar to manage credentials on the server(s).  I'll send out an email on that shortly, but wanted to get this on your radars to stave this off.

**Comment by egortimofeev** [comment]
chris, thank you. it is working, we will link it to GB to send all mails.

**Comment by rugly** [comment]
@egortimofeev no problem, but I'll take credit for it :)  It's the little things, right?  I'll add myself to the project so that I appear as myself once I get a Git organization set up, here in the coming week.  - Jeff

**Comment by Jenelle-SEO** [comment]
Egor - email is not sending upon registration.  Please double check.
