### ISSUE TITLE
Score User Submissions

### ISSUE THREAD

**Issue by seobrand** [egortimofeev/genius#9]
Upon completion of the questionnaire, calculate the user's score and redirect them to the appropriate screen.  If successful present them with the TOS, if not direct them to their profile screen and advise them they can try again in 2 weeks.

**Comment by egortimofeev** [comment]
can we define proper workflow? we have pages:
1) be a genius where you specify your email address
2) then it verifies this email by sending you a link
3) click on link you get thank you for verification page
4) page with detailed information about account (firstname, lastname, password - seems it will be autogenerated)
5) questions page
6) accept terms page
can you give a draft of dev registration flow? what is needed and what can be removed?
